footprint: [[0.3, 0.3], [-0.3, 0.3], [-0.3, -0.3], [0.3, -0.3]]
robot_radius: 0.3
inflation_radius: 0.5
obstacle_range: 2.5
raytrace_range: 3.0

custom_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  publish_frequency: 5.0
  transform_tolerance: 0.5

  plugins:
    - {name: static_layer,    type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  static_layer:
    enabled: true

  obstacle_layer:
    enabled: true
    max_obstacle_height: 0.6
    obstacle_range: 2.5
    raytrace_range: 3.0
    combination_method: 1                    # 1 = 最大值覆盖，保证障碍物不会重复叠加
    footprint_clearing_enabled: false        # 禁用基于机器人足迹的清除（改用圆形）
    track_unknown_space: true                # 允许更新未知区域
    observation_sources: laser_scan          # 指定数据源名称
    laser_scan: {sensor_frame: base_laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}

  inflation_layer:
    enabled: true
    inflation_radius: 0.5